### PR TITLE
Features

### PR DESCRIPTION
**Pull request by thedekerone**
**In this pull request:**

- We create the entire landing page using bootstrap.
- We use a grid layout for the entire main page and navbar class for the navigation.

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello @thedekerone 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️
On the main section:

- [ ] Missing 'the debate' title here, consider add it and put the bold in the 'by someone' as the original page.




- [ ] Consider made 'more stories' as the original page. 





- [ ] Consider made this image bigger than the others as the original page.


- [ ] 'Editor's Pick' and 'In the Magazine' title has to be bold and with the same font size. ([link](https://www.newsweek.com/) to the page).

- [ ] Consider fixing this section: missing bold, same size and links here as the original page. 





- [ ] Consider adding the bold and color as the original page.





- [ ] Mising 'culture & travel" section:


On the footer section:

- [ ] 'Newsweek' logo has to be a link.

- [ ] The main navigation has to be 'links'.

- [ ] Made margin between the logo and the copyright.

- [ ] Made a margin-bottom on the main navigation. 

On the tablet version:

- [ ] Consider fix this extra space as the original page:


- [ ] Consider fix this extra space as the original page:


- [ ] This has to be center and with the same width as the original page. 




- [ ] 'editor's pick' has to be in 2 columns, consider fix this.




- [ ] Consider made the distribution as the original page.




- [ ] Consider made this section and the footer as the original page, including bold and color.




On the mobile version:

- [ ] The order after 'top story' should be: 'featured stories', 'opinion', 'the debate', 'more stories', 'HEROES OF THE PANDEMIC', 'CULTURE & TRAVEL', and 'LATEST NEWS'. Consider fixing the order as the original page.


- [ ] Make this center and with the same as the original page.


- [ ] The image and the text have to with the same width here, consider fixing this.




- [ ] Consider fix this entire section, it is not as the original page.




- [ ] The 'subscribe' and 'newsletter' section has to be as the original page, consider fix all the details.


- [ ] Consider made more margin between the logo and the copyright.

- [ ] Consider made more margin-bottom on the footer.

- [ ] Consider fix the validator error.

- [ ] Missing 'demo link' on the readme file.

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright) 
---> no repeating of the same rule.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @thedekerone 
### You have done good so far :clap: and for also making changes from the previous reviews. However, you have a few issues to work on.
- Validate your html code and solve the raised issues, use [this link](https://validator.w3.org/#validate_by_upload)
validator 
- Remove the unwanted spaces on the left and right on more stories, make the height relative and scrollable
unwanted spaces left and right
- On responsive, remove the horizontal scrollbar
- You can some margin to separate the elements on responsive devices and any other place necessary
responsive margin
- On mobile devices, editors pick should go full width
responsive device
### Put more work on responsive features, target large screens, medium and small
### make all these changes and resubmit for another code review. Good luck.
- happy coding

**Comment by thedekerone** [comment]
Sorry i commited the changes but i forgot to push them. I fixed those
errors.

**Comment by thedekerone** [comment]
Can you check it again or do i have to send another code review?

**Comment by uryelah** [comment]
Hello **Fow Fow Aranibar**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Great job fixing the required changes from the last reviews. The project looks great and has adequated usage of Bootstrap classes and breaking points. 

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----


**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
